services:

  # # 3. Redis (Cache)
  redis:
    image: redis:8.6.1-trixie
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${redis_password}
    volumes:
      - redis_data:/data
    networks:
      - backend_private_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${redis_password}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Google Cloud SQL Auth Proxy (Containerized!)
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    container_name: rag_db_proxy
    restart: unless-stopped
    # Uses your .env variables to build the strict connection string
    command: >
      --address 0.0.0.0
      --port 5432
      ${gcp_project_id}:${gcp_region}:${cloud_sql_instance_name}
    networks:
      - backend_private_network

  # 3. The Celery Worker (Pulling from your new Artifact Registry!)
  worker:
    image: europe-west4-docker.pkg.dev/agents-platform-490417/agent-platform-repo/rag-engine-base:latest
    container_name: prod_worker
    restart: unless-stopped
    command: celery -A celery_tasks.tasks worker --loglevel=info
    env_file:
      - .env
    environment:
      # Point the worker to the internal Docker proxy container
      - db_host=cloud-sql-proxy
      - db_port=5432
      - redis_host=redis
    depends_on:
      redis:
        condition: service_healthy
      cloud-sql-proxy:
        condition: service_started
    networks:
      - backend_private_network



volumes:
  redis_data:

networks:
  backend_private_network:
    driver: bridge



# 2. RAG DB (Vector Database)
  # postgres_rag:
  #   image: pgvector/pgvector:0.8.2-pg18-trixie
  #   container_name: postgres_rag
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${RAG_POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${RAG_POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${RAG_POSTGRES_DB}
  #   ports:
  #     - "5433:5432" # Maps laptop port 5433 to container port 5432
  #   volumes:
  #     - postgres_rag_data:/var/lib/postgresql # Uses a brand new volume
  #   networks:
  #     - backend_private_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $RAG_POSTGRES_USER -d $RAG_POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s