"""add unique constraint

Revision ID: 03c97ddfd757
Revises: 70cff7cc0dc7
Create Date: 2026-03-10 05:23:03.481760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c97ddfd757'
down_revision: Union[str, Sequence[str], None] = '70cff7cc0dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_containers', 'company_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint('uix_company_container_name', 'knowledge_containers', ['company_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_container_name', 'knowledge_containers', type_='unique')
    op.alter_column('knowledge_containers', 'company_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
