"""Initial RAG tables

Revision ID: 70cff7cc0dc7
Revises: 
Create Date: 2026-03-10 02:33:10.940682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = '70cff7cc0dc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # CRITICAL: Enable the vector extension first!
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    
    op.create_table('knowledge_containers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_containers_company_id'), 'knowledge_containers', ['company_id'], unique=False)
    op.create_index(op.f('ix_knowledge_containers_id'), 'knowledge_containers', ['id'], unique=False)
    op.create_table('document_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('gcp_storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['knowledge_containers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_assets_container_id'), 'document_assets', ['container_id'], unique=False)
    op.create_index(op.f('ix_document_assets_id'), 'document_assets', ['id'], unique=False)
    op.create_table('vector_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('container_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['knowledge_containers.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_chunks_container_id'), 'vector_chunks', ['container_id'], unique=False)
    op.create_index(op.f('ix_vector_chunks_document_id'), 'vector_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_vector_chunks_id'), 'vector_chunks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_chunks_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_document_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_container_id'), table_name='vector_chunks')
    op.drop_table('vector_chunks')
    op.drop_index(op.f('ix_document_assets_id'), table_name='document_assets')
    op.drop_index(op.f('ix_document_assets_container_id'), table_name='document_assets')
    op.drop_table('document_assets')
    op.drop_index(op.f('ix_knowledge_containers_id'), table_name='knowledge_containers')
    op.drop_index(op.f('ix_knowledge_containers_company_id'), table_name='knowledge_containers')
    op.drop_table('knowledge_containers')
    # Optional: Remove the extension on downgrade
    op.execute('DROP EXTENSION IF EXISTS vector;')
    # ### end Alembic commands ###
