"""add HNSW vector index

Revision ID: 7ebfd8967087
Revises: 03c97ddfd757
Create Date: 2026-03-11 03:04:56.285029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebfd8967087'
down_revision: Union[str, Sequence[str], None] = '03c97ddfd757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- 1. ADD THIS LINE: Force the database column to strictly 768 dimensions ---
    op.execute("ALTER TABLE vector_chunks ALTER COLUMN embedding TYPE vector(768);")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vector_chunks_embedding_hnsw', 'vector_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_chunks_embedding_hnsw', table_name='vector_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
